name: Deploy to EC2

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET  SDK
    - name: Set up .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    # Step 3: Build the .NET application
    - name: Build the application
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    # Step 4: Set up SSH to communicate with your EC2 instance
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 5: Copy the built files to the EC2 instance
    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no ./publish/* ec2-user@44.201.169.65:~/var/www/craftify/Craftify.Api/

    # Step 6: Build, publish, and restart the .NET application on EC2
    - name: Publish and restart API
      run: |
        ssh ec2-user@${{ secrets.HOST_DNS }} << 'EOF'
          # Navigate to the directory where the application is deployed
          cd ${{ secrets.TARGET_DIR }}
          
          # Restart the API service (ensure you have a systemd service set up)
          sudo systemctl restart craftify-api-service
          
          # Restart Nginx to ensure it picks up any changes
          sudo systemctl restart nginx
        EOF
