name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no ./publish/* ec2-user@44.201.169.65:/var/www/craftify/Craftify.Api

    - name: Publish and restart API
      run: |
        ssh ec2-user@44.201.169.65 << 'EOF'
          # Navigate to the directory where the application is deployed
          cd /var/www/craftify/Craftify.Api
          
          # Ensure the application is built and published
          dotnet publish -c Release -o /var/www/craftify/Craftify.Api/publish
          
          # Restart the API service (assuming you have a service setup for your API)
          sudo systemctl restart my-api-service
          
          # Restart Nginx to ensure it picks up any changes
          sudo systemctl restart nginx
        EOF
