name: Deploy to EC2
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build the application
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ensure destination directory exists
      run: ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST_DNS }} 'mkdir -p ~/var/www/craftify/Craftify.Api/publish'

    - name: Copy files via rsync
      run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./publish/ ec2-user@${{ secrets.HOST_DNS }}:~/var/www/craftify/Craftify.Api/publish/

    - name: Deploy and run the API
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST_DNS }} << 'EOF'
          set -e
          echo "Navigating to target directory..."
          cd ~/var/www/craftify/Craftify.Api/

          echo "Updating Code in EC2 intence from git"
          git pull
          
          echo "Navigating to publish dir"
          cd ~/var/www/craftify/Craftify.Api/publish/

          echo "Killing any running instance of the API..."
          pkill -f 'dotnet Craftify.Api.dll' || echo "No running instance found."

          echo "Starting the new instance of the API..."
          nohup dotnet Craftify.Api.dll > ~/var/www/craftify/Craftify.Api/publish/logs.txt 2>&1 &

          echo "Checking if the API started successfully..."
          sleep 5
          if ! pgrep -f 'dotnet Craftify.Api.dll' > /dev/null; then
            echo "Failed to start API. Checking logs..."
            cat ~/var/www/craftify/Craftify.Api/publish/logs.txt
            exit 1
          else
            echo "API started successfully"
          fi

          echo "Restarting Nginx to apply any changes..."
          sudo systemctl restart nginx

          echo "Checking Nginx status..."
          if ! sudo systemctl is-active --quiet nginx; then
            echo "Failed to restart Nginx. Checking logs..."
            sudo journalctl -u nginx -n 50 --no-pager
            exit 1
          else
            echo "Nginx restarted successfully"
          fi
        EOF
