name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no ./publish/* ec2-user@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}

    - name: Publish and restart API
      run: |
        ssh ec2-user@${{ secrets.HOST_DNS }} << 'EOF'


          # Navigate to the directory where the application is deployed
          cd ${TARGET_DIR}

          #Updating code form git
          git pull
          
          
          # Ensure the application is built and published
          dotnet publish -c Release -o ${TARGET_DIR}/publish
          
          # Restart the API service 
          sudo systemctl restart craftify-api-service
          
          # Restart Nginx to ensure it picks up any changes
          sudo systemctl restart nginx
        EOF
